config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
  resources :comments
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 2}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true
  validates :article, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  protect_from_forgery :only => [:update, :delete, :create]

  def index
    @articles = Article.all
    respond_to do |format|
      format.json { render json: { message: "All articles", articles: @articles }, status: :ok }
      format.html
    end
  end

  def show
    @article = Article.find(params[:id])
    respond_to do |format|
      format.json { render json: { message: "Article found", article: @article, comments: @article.comments }, status: :ok }
      format.html 
    end
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Not found" }, status: :not_found }
        format.html 
      end
  end

  def new
    @article = Article.new()
  end

  def create
    article = Article.create(article_params)
    if article.save
      respond_to do |format|
        format.json { render json: { message: "Article created", article: article }, status: :ok }
        format.html { redirect_to article}
      end
    else
      respond_to do |format|
        format.json { render json: { message: article.errors }, status: :unprocessable_entity  }
        format.html { redirect_to new_article_path }
      end                 
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    respond_to do |format|
      if article.destroy
        format.json { render json: { article: article }, status: :ok }
        format.html { redirect_to articles_path}
      else
        format.json { render json: { message: article.errors }, status: :unprocessable_entity }
        format.html { redirect_to article_path }
      end 
    end 
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Not found" }, status: :not_found }
        format.html 
      end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    if article.update_attributes(article_params)
      respond_to do |format|
        format.json { render json: { message: "Article updated", article: article}, status: :ok }
        format.html { redirect_to article_path }
      end 
    else                    
      respond_to do |format|
        format.json { render json: { message: article.errors }, status: :unprocessable_entity }
        format.html { redirect_to article_path }
      end 
    end 
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Not found" }, status: :not_found }
        format.html 
      end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  protect_from_forgery :only => [:update, :delete, :create]

  def index
    @comments = Comment.all
    respond_to do |format|
      format.json { render json: { message: "All comments", comments: @comments }, status: :ok }
      format.html
    end
  end

  def show
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.json { render json: { message: "Loaded comment", comment: @comment }, status: :ok }
      format.html 
    end
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Not found" }, status: :not_found }
        format.html 
      end
  end

  def new
    @comment = Comment.new(comment_params)
  end

  def create
    @article = Article.find(comment_params[:article_id])
    @comment = Comment.create(comment_params)
    if @comment.save
      respond_to do |format|
        format.json { render json: { message: "Added comment", comment: @comment }, status: :ok }
        format.html { redirect_to article_path(@article) }
      end
    else
      respond_to do |format|
        format.json { render json: { message: comment.errors}, status: :unprocessable_entity }
        format.html { redirect_to articles_path }
      end
    end
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Article not found" }, status: :not_found }
        format.html 
      end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])
    if comment.update_attributes(params.require('comment').permit(:commenter, :body))
      respond_to do |format|
        format.json { render json: { message: "Comment updated", comment: comment}, status: :ok }
        format.html { redirect_to articles_path }
      end 
    else                    
      respond_to do |format|
        format.json { render json: { message: comment.errors}, status: :unprocessable_entity }
        format.html { redirect_to articles_path }
      end 
    end 
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Not found" }, status: :not_found }
        format.html 
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.destroy
        format.json { render json: { message: "Comment deleted!", comment: @comment }, status: :ok }
        format.html { redirect_to articles_path }
      else
        format.json { render json: { message: @comment.errors }, status: :unprocessable_entity }
        format.html { redirect_to articles_path }
      end
    end
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: { message: "Comment not found" }, status: :not_found }
        format.html { redirect_to article_path(@article) }
      end
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :article_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article,local: true do |form| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
  </h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<p>
  <%= form.label :title %><br>
  <%= form.text_field :title, :class => 'form-control'%>
</p>
<p>
  <%= form.label :text %><br>
  <%= form.text_area :text, :class => 'form-control' %>
</p>
<p>
  <center><%= form.submit 'Save', :class => 'btn btn-lg btn-primary' %></center>
</p>
<% end %>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit post</title>
</head>
<body>
  <div class="container">
    <h1>Edit article</h1>
    <%= render 'form' %> 
    <%= link_to 'Back', articles_path, class: 'btn btn-lg btn-primary' %>
  </div>
</body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
</head>
<body>
  <div class = 'container'>
    <center><h1>Posts</h1></center>
    <% @articles.each do |article| %>
    <h2><%= article.title %></h2>
    <p><%= article.text %></p>
    <p>
      <%= link_to 'Show', article_path(article), class: 'btn btn-md btn-success'%>
      <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-md btn-primary' %>
      <%= link_to 'Destroy', article_path(article), class: 'btn btn-md btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <hr>
    <% end %>
    <%= link_to 'Add article', new_article_path, class: 'btn btn-md btn-info' %>
    <%= link_to 'Home', root_path, class: 'btn btn-md btn-info' %>
  </div>
</body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Add Article</title>
</head>
<body>
  <div class="container">
    <h1>New Article</h1>
    <%= render 'form' %>
    <%= link_to 'Back', articles_path %>
  </div>
</body>
</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
</head>
<body>
  <div class="container">
    <center><h2><%= @article.title %></h2></center>
    <p><%= @article.text %></p>
    <br><br>
    <h3>Comments</h3>
    <% comments = Comment.where(article: @article[:id]) %>
    <%= render comments %>
    <h4>Add a comment:</h4>
    <%= render 'comments/form' %>
    <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-md btn-primary' %>
    <%= link_to 'Back', articles_path, class: 'btn btn-md btn-primary' %>
  </div>
</body>
</html>

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %> : </strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Edit Comment', edit_comment_path(comment) %>	<br>
  <%= link_to 'Destroy Comment', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<hr>

app/views/comments/_form.html.erb
<%= form_for Comment.new, url: '/comments', local: true do |form| %>
<p>
  <%= form.label :commenter %><br>
  <%= form.text_field :commenter, :class => 'form-control' %>
</p>
<p>
  <%= form.label :body %><br>
  <%= form.text_area :body, :class => 'form-control' %>
</p>
    <%= form.hidden_field :article_id, :value => @article[:id] %>
<p>
  <%= form.submit "Comment", :class =>'btn btn-md btn-success' %>
</p>
<% end %>

app/views/comments/edit.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
<p>
  <%= form.label :commenter %><br>
  <%= form.text_field :commenter, :class => 'form-control' %>
</p>
<p>
  <%= form.label :body %><br>
  <%= form.text_area :body, :class => 'form-control' %>
</p>
<p>
  <%= form.submit "Comment", :class =>'btn btn-md btn-success' %>
</p>
<% end %>

app/views/comments/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
</head>
<body>
  <div class = 'container'>
    <center><h1>Comments</h1></center>
    <% @comments.each do |comment| %>
    <h2><%= comment.commenter %></h2>
    <p><%= comment.body %></p>
    <p>
      <%= link_to 'Show', comment_path(comment), class: 'btn btn-md btn-success'%>
      <%= link_to 'Edit', edit_comment_path(comment), class: 'btn btn-md btn-primary' %>
      <%= link_to 'Destroy', comment_path(comment), class: 'btn btn-md btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <hr>
    <% end %>
  </div>
</body>
</html>

app/views/comments/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
</head>
<body>
  <div class="container">
    <center><h2><%= @comment.commenter %></h2></center>
    <p><%= @comment.body %></p>
    <%= link_to 'Edit', edit_comment_path(@comment), class: 'btn btn-md btn-primary' %>
    <%= link_to 'Back', comments_path, class: 'btn btn-md btn-primary' %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
</head>
<body>
  <div class="container">
    <div class="center jumbotron">
      <center>
        <h1>Welcome to My Blog</h1>
          <%= link_to 'Enter here', 'articles', class: 'btn btn-lg btn-primary'%>
      </center>
    </div>
  </div>
</body>
</html>